Update building and running workflows
unikraft/app-sqlite pull request #9
Opened 2023-07-01 10:55 UTC by StefanJum

* Add default minimal configs that can be used as staring point
* Add running scripts
* Change `UK_ROOT` and `UK_LIBS` to point to `$(PWD)/.unikraft/...` [TODO]: Add README.md file

2023-07-02 21:10 UTC, razvand requested changes
Add `.gitignore` file to ignore output files.

2023-07-02 21:10 UTC, razvand commented on README.md
> +* `qemu-system-x86`
```suggestion
* `qemu-system-x86`
* `qemu-system-arm`
```

2023-07-02 21:10 UTC, razvand commented on README.md
> +  qemu-system-x86 \
```suggestion
  qemu-system-x86 \
  qemu-system-arm \
```

2023-07-02 21:10 UTC, razvand commented on README.md
> +$ apt-get install -y --no-install-recommends \
```suggestion
$ sudo apt install -y --no-install-recommends \
```

2023-07-02 21:10 UTC, razvand commented on Makefile
> +
```suggestion
```

2023-07-02 21:10 UTC, razvand commented on Makefile.uk
> +
```suggestion
```

2023-07-03 05:42 UTC, StefanJum commented
Done @razvand

2023-07-03 10:59 UTC, razvand requested changes
Thanks, @StefanJum. See my comments.

2023-07-03 10:59 UTC, razvand commented on run-qemu-aarch64.sh
> +#!/bin/bash
```suggestion
#!/bin/sh
```

2023-07-03 10:59 UTC, razvand commented on run-qemu-x86_64.sh
> +#!/bin/bash
```suggestion
#!/bin/sh
```

2023-07-03 10:59 UTC, razvand commented on run-qemu-x86_64.sh
> +sudo /usr/bin/qemu-system-x86_64 \
```suggestion
/usr/bin/qemu-system-x86_64 \
```

2023-07-03 10:59 UTC, razvand commented on run-qemu-aarch64.sh
> +sudo /usr/bin/qemu-system-aarch64 \
```suggestion
/usr/bin/qemu-system-aarch64 \
```

2023-07-03 12:34 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-07-03 12:47 UTC, closed without merging